//
//  HomeModels.swift
//  Pokedex
//
//  Created by Javier Paez Arcos on 26/08/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
    // MARK: Use cases
    
    enum FetchPokemonData
    {
        struct Request
        {
            
        }
        
        struct Response
        {
            let pokemons: [PokemonEntry]
        }
        
        struct ViewModel
        {
            let pokemons: [PokemonEntry]
        }
    }
    
    enum ShowPokemonDetails
    {
        struct Request
        {
            let pokemonData: PokemonData
        }
        
        struct Response
        {
        }
        
        struct ViewModel
        {
        }
    }
    
    enum SearchByTypeSelected {
        struct Request
        {
            
        }
        
        struct Response
        {
            let typeString: String
        }
        
        struct ViewModel
        {
            let typeString: String
        }
    }
}
