//
//  HomeRouter.swift
//  Pokedex
//
//  Created by Javier Paez Arcos on 26/08/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func routeToDetails()
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
    
    
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?

// MARK: Routing (navigating to other screens)

    func routeToDetails() {
        let destinationVC = DetailsViewController()
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDetails(source: dataStore!, destination: &destinationDS)
        navigateToDetails(source: viewController!, destination: destinationVC)
        
    }

    // MARK: Navigation to other screen
    
    func navigateToDetails(source: HomeViewController, destination: DetailsViewController) {
        source.show(destination, sender: nil)
    }
        
    // MARK: Passing data to other screen
        
    func passDataToDetails(source: HomeDataStore, destination: inout DetailsDataStore) {
        destination.pokemonData = source.pokemonData
    }
}
