//
//  HomePresenter.swift
//  Pokedex
//
//  Created by Javier Paez Arcos on 26/08/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentPokemons(response: Home.FetchPokemonData.Response)
    func presentPokemonDetails(response: Home.ShowPokemonDetails.Response)
    func presentSearchByTypeSelected(response: Home.SearchByTypeSelected.Response)
}

class HomePresenter: HomePresentationLogic {
    
    
    weak var viewController: HomeDisplayLogic?

    // MARK: Parse and calc respnse from HomeInteractor and send simple view model to HomeViewController to be displayed

    func presentPokemons(response: Home.FetchPokemonData.Response) {
        let viewModel = Home.FetchPokemonData.ViewModel(pokemons: response.pokemons)
        viewController?.displayPokemons(viewModel: viewModel)
    }
    
    func presentPokemonDetails(response: Home.ShowPokemonDetails.Response) {
        let viewModel = Home.ShowPokemonDetails.ViewModel()
        viewController?.displayPokemonDetails(viewModel: viewModel)
    }
    
    func presentSearchByTypeSelected(response: Home.SearchByTypeSelected.Response) {
        let viewModel = Home.SearchByTypeSelected.ViewModel(typeString: response.typeString)
        viewController?.displaySearchByTypeSelected(viewModel: viewModel)
    }
}
