//
//  HomeWorker.swift
//  Pokedex
//
//  Created by Javier Paez Arcos on 26/08/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker {
    func fetchPokemonDataWork(completionHandler: @escaping([PokemonEntry]) -> Void) {
        NetworkManager.shared.fetchPokemonData { result in
            switch result {
            case .success(let pokemonEntries):
                
                pokemonEntries.forEach { pokemonEntry in
                    
                }
                completionHandler(pokemonEntries)
                
            case .failure(_):
                print("error")
                
            }
        }
    }
    
    
    func fetchPokemonUrlWork(completionHandler: @escaping([PokemonSprites])-> Void) {
        
    }
}
