//
//  DetailsRouter.swift
//  Pokedex
//
//  Created by Javier Paez Arcos on 30/08/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailsRoutingLogic {
    func routeToHome()
}

protocol DetailsDataPassing {
    var dataStore: DetailsDataStore? { get }
}

class DetailsRouter: NSObject, DetailsRoutingLogic, DetailsDataPassing {
    weak var viewController: DetailsViewController?
    var dataStore: DetailsDataStore?

// MARK: Routing (navigating to other screens)

    func routeToHome() {
        
        let a = viewController?.previousViewController as! HomeViewController
        //let destinationVC = HomeViewController()
        var destinationDS = a.router!.dataStore!
        passDataToHome(source: dataStore!, destination: &destinationDS)
        navigateToHome(source: viewController!, destination: a)
        
    }

    // MARK: Navigation to other screen
    
    func navigateToHome(source: DetailsViewController, destination: HomeViewController) {
        
       source.navigationController?.popViewController(animated: true)
       //source.show(destination, sender: nil)
        //source.dismiss(animated: true, completion: nil)
    }
        
    // MARK: Passing data to other screen
        
    func passDataToHome(source: DetailsDataStore, destination: inout HomeDataStore) {
        
        destination.typeSelected = source.typeSelected
        
    }
}

extension UIViewController{
   var previousViewController:UIViewController?{
        if let controllersOnNavStack = self.navigationController?.viewControllers, controllersOnNavStack.count >= 2 {
            let n = controllersOnNavStack.count
            return controllersOnNavStack[n - 2]
        }
        return nil
    }
}
