//
//  DetailsPresenter.swift
//  Pokedex
//
//  Created by Javier Paez Arcos on 30/08/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsPresentationLogic {
    func presentBackToSearchByTypeString(response: Details.BackToSearchByTypeSelected.Response)
}

class DetailsPresenter: DetailsPresentationLogic {
    weak var viewController: DetailsDisplayLogic?

    // MARK: Parse and calc respnse from DetailsInteractor and send simple view model to DetailsViewController to be displayed

    func presentBackToSearchByTypeString(response: Details.BackToSearchByTypeSelected.Response) {
        let viewModel = Details.BackToSearchByTypeSelected.ViewModel()
        viewController?.displayBackToSearchByTypeString(viewModel: viewModel)
    }
}
